# Generated by Django 5.1.7 on 2025-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.IntegerField(),
        ),
    ]
